version: "3"

services:
  unpa.la:
    build: .
    labels:
      - traefik.http.routers.unpa.rule=Host(`unpa.la`)
      - traefik.http.routers.unpa.tls=true
      - traefik.http.routers.unpa.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - server

networks:
  server:
    external: true
